name: Build and Publish .NET API with Angular

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore HelloAngular/HelloAngular.csproj

    - name: Build
      run: dotnet build HelloAngular/HelloAngular.csproj --no-restore

    - name: test
      run: dotnet test HelloAngular/HelloAngular.csproj --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish HelloAngular/HelloAngular.csproj p-GHPages=true -o public/angular -c Release
           
    - name: Deploy
        uses:  azure/webapps-deploy@v1
        with:
          app-name: angular 
          package: './public/angular' 

