name: Build and Publish Blazor WebAssembly in .NET 6

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore HelloBlazor/HelloBlazor.csproj

    - name: Build
      run: dotnet build HelloBlazor/HelloBlazor.csproj --no-restore

    - name: test
      run: dotnet test HelloBlazor/HelloBlazor.csproj --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish HelloBlazor/HelloBlazor.csproj p:GHPages=true -o:public/blazor -c Release



