name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore HelloBlazor/HelloBlazor/HelloBlazor.csproj
    - name: Publish
      run: dotnet publish HelloBlazor/HelloBlazor/HelloBlazor.csproj -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
